const $=id=>document.getElementById(id);const moduleGrid=$('moduleGrid'),panel=$('panel'),panelTitle=$('panelTitle'),panelBody=$('panelBody'),reply=$('assistantReply'),input=$('commandInput'),status=$('coreStatus');renderModules();
function setReply(text,speak=false){reply.innerHTML='<span class="prompt">VAULT //</span> '+escapeHtml(text);if(speak&&'speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.96;speechSynthesis.speak(u)}}
function run(fromVoice=false){const command=input.value;status.textContent='PROCESSING';const answer=vaultCommand(command);VaultDB.add('conversation',command,{role:'user'});VaultDB.add('conversation',answer,{role:'vault'});setReply(answer,fromVoice);input.value='';setTimeout(()=>status.textContent='STANDBY',650)}
$('sendBtn').addEventListener('click',()=>run(false));input.addEventListener('keydown',e=>{if(e.key==='Enter')run(false)});$('coreBtn').addEventListener('click',()=>{input.focus();status.textContent='AWAITING COMMAND';setReply('Je vous écoute.')});$('closePanel').addEventListener('click',()=>panel.classList.add('hidden'));$('quickAdd').addEventListener('click',()=>openModule('notes'));
$('voiceBtn').addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setReply('La reconnaissance vocale n’est pas disponible dans ce navigateur. Vous pouvez utiliser la commande écrite.');return}const r=new SR();r.lang='fr-FR';r.interimResults=false;status.textContent='LISTENING';$('voiceBtn').classList.add('listening');setReply('Écoute en cours…');r.onresult=e=>{input.value=e.results[0][0].transcript;run(true)};r.onerror=()=>{setReply('Je n’ai pas pu entendre la commande.');status.textContent='STANDBY'};r.onend=()=>{$('voiceBtn').classList.remove('listening');if(status.textContent==='LISTENING')status.textContent='STANDBY'};r.start()});
function showSearch(){panelTitle.textContent='RECHERCHE GLOBALE';panel.classList.remove('hidden');panelBody.innerHTML='<div class="add-row"><input id="globalSearch" placeholder="Rechercher dans VAULT…"><button id="globalSearchBtn">RECHERCHER</button></div><div id="searchResults"><p>Recherche dans Notes, Tâches, Projets et Inventaire.</p></div>';const go=()=>{const q=$('globalSearch').value,r=VaultDB.search(q);$('searchResults').innerHTML=r.length?r.map(x=>`<div class="item"><b>${x.label}</b><br>${escapeHtml(x.text)}<br><small>${x.date}</small></div>`).join(''):'<p>Aucun résultat.</p>'};$('globalSearchBtn').addEventListener('click',go);$('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter')go()});$('globalSearch').focus()}
function showSystem(){const s=VaultDB.stats();panelTitle.textContent='SYSTÈME';panel.classList.remove('hidden');panelBody.innerHTML=`<div class="item"><b>VAULT OS 1.2</b><br><small>MEMORY CORE // LOCAL</small></div><div class="item">Notes : ${s.notes}<br>Tâches : ${s.tasks}<br>Projets : ${s.projects}<br>Inventaire : ${s.inventory}</div><div class="item">Réseau : ${navigator.onLine?'ONLINE':'OFFLINE'}<br>Stockage : cet appareil</div>`}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.nav;if(n==='home'){panel.classList.add('hidden');scrollTo({top:0,behavior:'smooth'})}else if(n==='assistant'){input.focus();setReply('Canal de commande actif.')}else if(n==='search')showSearch();else showSystem()}));
const h=new Date().getHours();$('greeting').textContent=h<12?'Bonjour.':h<18?'Bon après-midi.':'Bonsoir.';function updateNetwork(){$('netState').textContent=navigator.onLine?'ONLINE':'OFFLINE'}window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);updateNetwork();setTimeout(()=>$('bootLine').textContent='LOADING MEMORY…',400);setTimeout(()=>$('bootLine').textContent='SYSTEM ONLINE',900);setTimeout(()=>$('boot').classList.add('done'),1400);
if('serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js?v=12').then(r=>r.update())}
